// GENERATED by tools/gen_symbols.py — do not edit
//
// Source: pylatexenc `latex2text/_defaultspecs.py`, `unicode_accents_list`,
// plus the composition and spacing-clone facts of the unicode database.

//! The accent tables (PLAN.md §9.3, §12.4).
//!
//! Three tables, all sorted so that they can be searched by bisection, and all
//! written with escaped characters so that a combining mark cannot be mangled
//! by an editor: what each accent macro installs, what a mark looks like on its
//! own, and what a (base, mark) pair composes to.

/// The accent macros and the combining mark each one installs.
///
/// Sorted by macro name. The name is written without its escape character, as
/// techy registers it: `"'"` is `\'`.
pub(crate) static ACCENTS: &[(&str, char)] = &[
    ("\"", '\u{0308}'), // COMBINING DIAERESIS
    ("'", '\u{0301}'), // COMBINING ACUTE ACCENT
    (".", '\u{0307}'), // COMBINING DOT ABOVE
    ("=", '\u{0304}'), // COMBINING MACRON
    ("H", '\u{030b}'), // COMBINING DOUBLE ACUTE ACCENT
    ("^", '\u{0302}'), // COMBINING CIRCUMFLEX ACCENT
    ("`", '\u{0300}'), // COMBINING GRAVE ACCENT
    ("acute", '\u{0301}'), // COMBINING ACUTE ACCENT
    ("b", '\u{0331}'), // COMBINING MACRON BELOW
    ("bar", '\u{0305}'), // COMBINING OVERLINE
    ("breve", '\u{0306}'), // COMBINING BREVE
    ("c", '\u{0327}'), // COMBINING CEDILLA
    ("check", '\u{030c}'), // COMBINING CARON
    ("d", '\u{0323}'), // COMBINING DOT BELOW
    ("ddot", '\u{0308}'), // COMBINING DIAERESIS
    ("dot", '\u{0307}'), // COMBINING DOT ABOVE
    ("grave", '\u{0300}'), // COMBINING GRAVE ACCENT
    ("hat", '\u{0302}'), // COMBINING CIRCUMFLEX ACCENT
    ("k", '\u{0328}'), // COMBINING OGONEK
    ("not", '\u{0338}'), // COMBINING LONG SOLIDUS OVERLAY
    ("r", '\u{030a}'), // COMBINING RING ABOVE
    ("tilde", '\u{0303}'), // COMBINING TILDE
    ("u", '\u{0306}'), // COMBINING BREVE
    ("v", '\u{030c}'), // COMBINING CARON
    ("vec", '\u{20d7}'), // COMBINING RIGHT ARROW ABOVE
    ("~", '\u{0303}'), // COMBINING TILDE
];

/// The standalone (spacing) form of a combining mark, where unicode has one.
///
/// Sorted by the combining mark. A mark that is missing here has no standalone
/// form, and PLAN.md §9.3's fallback — a space followed by the mark — applies.
pub(crate) static ACCENT_SPACING: &[(char, char)] = &[
    ('\u{0300}', '\u{0060}'), // COMBINING GRAVE ACCENT → GRAVE ACCENT
    ('\u{0301}', '\u{00b4}'), // COMBINING ACUTE ACCENT → ACUTE ACCENT
    ('\u{0302}', '\u{005e}'), // COMBINING CIRCUMFLEX ACCENT → CIRCUMFLEX ACCENT
    ('\u{0303}', '\u{02dc}'), // COMBINING TILDE → SMALL TILDE
    ('\u{0304}', '\u{00af}'), // COMBINING MACRON → MACRON
    ('\u{0305}', '\u{203e}'), // COMBINING OVERLINE → OVERLINE
    ('\u{0306}', '\u{02d8}'), // COMBINING BREVE → BREVE
    ('\u{0307}', '\u{02d9}'), // COMBINING DOT ABOVE → DOT ABOVE
    ('\u{0308}', '\u{00a8}'), // COMBINING DIAERESIS → DIAERESIS
    ('\u{030a}', '\u{02da}'), // COMBINING RING ABOVE → RING ABOVE
    ('\u{030b}', '\u{02dd}'), // COMBINING DOUBLE ACUTE ACCENT → DOUBLE ACUTE ACCENT
    ('\u{030c}', '\u{02c7}'), // COMBINING CARON → CARON
    ('\u{0327}', '\u{00b8}'), // COMBINING CEDILLA → CEDILLA
    ('\u{0328}', '\u{02db}'), // COMBINING OGONEK → OGONEK
];

/// Every (base, mark) pair that composes to a single character under NFC.
///
/// Sorted by `(base, mark)`. This is the whole of the unicode normalization
/// techxt needs: a `no_std` crate carries no unicode database, and the accent
/// rule only ever composes one base character with one of the marks above.
pub(crate) static ACCENT_COMPOSITIONS: &[(char, char, char)] = &[
    ('\u{003c}', '\u{0338}', '\u{226e}'), // NOT LESS-THAN
    ('\u{003d}', '\u{0338}', '\u{2260}'), // NOT EQUAL TO
    ('\u{003e}', '\u{0338}', '\u{226f}'), // NOT GREATER-THAN
    ('\u{0041}', '\u{0300}', '\u{00c0}'), // LATIN CAPITAL LETTER A WITH GRAVE
    ('\u{0041}', '\u{0301}', '\u{00c1}'), // LATIN CAPITAL LETTER A WITH ACUTE
    ('\u{0041}', '\u{0302}', '\u{00c2}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    ('\u{0041}', '\u{0303}', '\u{00c3}'), // LATIN CAPITAL LETTER A WITH TILDE
    ('\u{0041}', '\u{0304}', '\u{0100}'), // LATIN CAPITAL LETTER A WITH MACRON
    ('\u{0041}', '\u{0306}', '\u{0102}'), // LATIN CAPITAL LETTER A WITH BREVE
    ('\u{0041}', '\u{0307}', '\u{0226}'), // LATIN CAPITAL LETTER A WITH DOT ABOVE
    ('\u{0041}', '\u{0308}', '\u{00c4}'), // LATIN CAPITAL LETTER A WITH DIAERESIS
    ('\u{0041}', '\u{030a}', '\u{00c5}'), // LATIN CAPITAL LETTER A WITH RING ABOVE
    ('\u{0041}', '\u{030c}', '\u{01cd}'), // LATIN CAPITAL LETTER A WITH CARON
    ('\u{0041}', '\u{0323}', '\u{1ea0}'), // LATIN CAPITAL LETTER A WITH DOT BELOW
    ('\u{0041}', '\u{0328}', '\u{0104}'), // LATIN CAPITAL LETTER A WITH OGONEK
    ('\u{0042}', '\u{0307}', '\u{1e02}'), // LATIN CAPITAL LETTER B WITH DOT ABOVE
    ('\u{0042}', '\u{0323}', '\u{1e04}'), // LATIN CAPITAL LETTER B WITH DOT BELOW
    ('\u{0042}', '\u{0331}', '\u{1e06}'), // LATIN CAPITAL LETTER B WITH LINE BELOW
    ('\u{0043}', '\u{0301}', '\u{0106}'), // LATIN CAPITAL LETTER C WITH ACUTE
    ('\u{0043}', '\u{0302}', '\u{0108}'), // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    ('\u{0043}', '\u{0307}', '\u{010a}'), // LATIN CAPITAL LETTER C WITH DOT ABOVE
    ('\u{0043}', '\u{030c}', '\u{010c}'), // LATIN CAPITAL LETTER C WITH CARON
    ('\u{0043}', '\u{0327}', '\u{00c7}'), // LATIN CAPITAL LETTER C WITH CEDILLA
    ('\u{0044}', '\u{0307}', '\u{1e0a}'), // LATIN CAPITAL LETTER D WITH DOT ABOVE
    ('\u{0044}', '\u{030c}', '\u{010e}'), // LATIN CAPITAL LETTER D WITH CARON
    ('\u{0044}', '\u{0323}', '\u{1e0c}'), // LATIN CAPITAL LETTER D WITH DOT BELOW
    ('\u{0044}', '\u{0327}', '\u{1e10}'), // LATIN CAPITAL LETTER D WITH CEDILLA
    ('\u{0044}', '\u{0331}', '\u{1e0e}'), // LATIN CAPITAL LETTER D WITH LINE BELOW
    ('\u{0045}', '\u{0300}', '\u{00c8}'), // LATIN CAPITAL LETTER E WITH GRAVE
    ('\u{0045}', '\u{0301}', '\u{00c9}'), // LATIN CAPITAL LETTER E WITH ACUTE
    ('\u{0045}', '\u{0302}', '\u{00ca}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    ('\u{0045}', '\u{0303}', '\u{1ebc}'), // LATIN CAPITAL LETTER E WITH TILDE
    ('\u{0045}', '\u{0304}', '\u{0112}'), // LATIN CAPITAL LETTER E WITH MACRON
    ('\u{0045}', '\u{0306}', '\u{0114}'), // LATIN CAPITAL LETTER E WITH BREVE
    ('\u{0045}', '\u{0307}', '\u{0116}'), // LATIN CAPITAL LETTER E WITH DOT ABOVE
    ('\u{0045}', '\u{0308}', '\u{00cb}'), // LATIN CAPITAL LETTER E WITH DIAERESIS
    ('\u{0045}', '\u{030c}', '\u{011a}'), // LATIN CAPITAL LETTER E WITH CARON
    ('\u{0045}', '\u{0323}', '\u{1eb8}'), // LATIN CAPITAL LETTER E WITH DOT BELOW
    ('\u{0045}', '\u{0327}', '\u{0228}'), // LATIN CAPITAL LETTER E WITH CEDILLA
    ('\u{0045}', '\u{0328}', '\u{0118}'), // LATIN CAPITAL LETTER E WITH OGONEK
    ('\u{0046}', '\u{0307}', '\u{1e1e}'), // LATIN CAPITAL LETTER F WITH DOT ABOVE
    ('\u{0047}', '\u{0301}', '\u{01f4}'), // LATIN CAPITAL LETTER G WITH ACUTE
    ('\u{0047}', '\u{0302}', '\u{011c}'), // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    ('\u{0047}', '\u{0304}', '\u{1e20}'), // LATIN CAPITAL LETTER G WITH MACRON
    ('\u{0047}', '\u{0306}', '\u{011e}'), // LATIN CAPITAL LETTER G WITH BREVE
    ('\u{0047}', '\u{0307}', '\u{0120}'), // LATIN CAPITAL LETTER G WITH DOT ABOVE
    ('\u{0047}', '\u{030c}', '\u{01e6}'), // LATIN CAPITAL LETTER G WITH CARON
    ('\u{0047}', '\u{0327}', '\u{0122}'), // LATIN CAPITAL LETTER G WITH CEDILLA
    ('\u{0048}', '\u{0302}', '\u{0124}'), // LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    ('\u{0048}', '\u{0307}', '\u{1e22}'), // LATIN CAPITAL LETTER H WITH DOT ABOVE
    ('\u{0048}', '\u{0308}', '\u{1e26}'), // LATIN CAPITAL LETTER H WITH DIAERESIS
    ('\u{0048}', '\u{030c}', '\u{021e}'), // LATIN CAPITAL LETTER H WITH CARON
    ('\u{0048}', '\u{0323}', '\u{1e24}'), // LATIN CAPITAL LETTER H WITH DOT BELOW
    ('\u{0048}', '\u{0327}', '\u{1e28}'), // LATIN CAPITAL LETTER H WITH CEDILLA
    ('\u{0049}', '\u{0300}', '\u{00cc}'), // LATIN CAPITAL LETTER I WITH GRAVE
    ('\u{0049}', '\u{0301}', '\u{00cd}'), // LATIN CAPITAL LETTER I WITH ACUTE
    ('\u{0049}', '\u{0302}', '\u{00ce}'), // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    ('\u{0049}', '\u{0303}', '\u{0128}'), // LATIN CAPITAL LETTER I WITH TILDE
    ('\u{0049}', '\u{0304}', '\u{012a}'), // LATIN CAPITAL LETTER I WITH MACRON
    ('\u{0049}', '\u{0306}', '\u{012c}'), // LATIN CAPITAL LETTER I WITH BREVE
    ('\u{0049}', '\u{0307}', '\u{0130}'), // LATIN CAPITAL LETTER I WITH DOT ABOVE
    ('\u{0049}', '\u{0308}', '\u{00cf}'), // LATIN CAPITAL LETTER I WITH DIAERESIS
    ('\u{0049}', '\u{030c}', '\u{01cf}'), // LATIN CAPITAL LETTER I WITH CARON
    ('\u{0049}', '\u{0323}', '\u{1eca}'), // LATIN CAPITAL LETTER I WITH DOT BELOW
    ('\u{0049}', '\u{0328}', '\u{012e}'), // LATIN CAPITAL LETTER I WITH OGONEK
    ('\u{004a}', '\u{0302}', '\u{0134}'), // LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    ('\u{004b}', '\u{0301}', '\u{1e30}'), // LATIN CAPITAL LETTER K WITH ACUTE
    ('\u{004b}', '\u{030c}', '\u{01e8}'), // LATIN CAPITAL LETTER K WITH CARON
    ('\u{004b}', '\u{0323}', '\u{1e32}'), // LATIN CAPITAL LETTER K WITH DOT BELOW
    ('\u{004b}', '\u{0327}', '\u{0136}'), // LATIN CAPITAL LETTER K WITH CEDILLA
    ('\u{004b}', '\u{0331}', '\u{1e34}'), // LATIN CAPITAL LETTER K WITH LINE BELOW
    ('\u{004c}', '\u{0301}', '\u{0139}'), // LATIN CAPITAL LETTER L WITH ACUTE
    ('\u{004c}', '\u{030c}', '\u{013d}'), // LATIN CAPITAL LETTER L WITH CARON
    ('\u{004c}', '\u{0323}', '\u{1e36}'), // LATIN CAPITAL LETTER L WITH DOT BELOW
    ('\u{004c}', '\u{0327}', '\u{013b}'), // LATIN CAPITAL LETTER L WITH CEDILLA
    ('\u{004c}', '\u{0331}', '\u{1e3a}'), // LATIN CAPITAL LETTER L WITH LINE BELOW
    ('\u{004d}', '\u{0301}', '\u{1e3e}'), // LATIN CAPITAL LETTER M WITH ACUTE
    ('\u{004d}', '\u{0307}', '\u{1e40}'), // LATIN CAPITAL LETTER M WITH DOT ABOVE
    ('\u{004d}', '\u{0323}', '\u{1e42}'), // LATIN CAPITAL LETTER M WITH DOT BELOW
    ('\u{004e}', '\u{0300}', '\u{01f8}'), // LATIN CAPITAL LETTER N WITH GRAVE
    ('\u{004e}', '\u{0301}', '\u{0143}'), // LATIN CAPITAL LETTER N WITH ACUTE
    ('\u{004e}', '\u{0303}', '\u{00d1}'), // LATIN CAPITAL LETTER N WITH TILDE
    ('\u{004e}', '\u{0307}', '\u{1e44}'), // LATIN CAPITAL LETTER N WITH DOT ABOVE
    ('\u{004e}', '\u{030c}', '\u{0147}'), // LATIN CAPITAL LETTER N WITH CARON
    ('\u{004e}', '\u{0323}', '\u{1e46}'), // LATIN CAPITAL LETTER N WITH DOT BELOW
    ('\u{004e}', '\u{0327}', '\u{0145}'), // LATIN CAPITAL LETTER N WITH CEDILLA
    ('\u{004e}', '\u{0331}', '\u{1e48}'), // LATIN CAPITAL LETTER N WITH LINE BELOW
    ('\u{004f}', '\u{0300}', '\u{00d2}'), // LATIN CAPITAL LETTER O WITH GRAVE
    ('\u{004f}', '\u{0301}', '\u{00d3}'), // LATIN CAPITAL LETTER O WITH ACUTE
    ('\u{004f}', '\u{0302}', '\u{00d4}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    ('\u{004f}', '\u{0303}', '\u{00d5}'), // LATIN CAPITAL LETTER O WITH TILDE
    ('\u{004f}', '\u{0304}', '\u{014c}'), // LATIN CAPITAL LETTER O WITH MACRON
    ('\u{004f}', '\u{0306}', '\u{014e}'), // LATIN CAPITAL LETTER O WITH BREVE
    ('\u{004f}', '\u{0307}', '\u{022e}'), // LATIN CAPITAL LETTER O WITH DOT ABOVE
    ('\u{004f}', '\u{0308}', '\u{00d6}'), // LATIN CAPITAL LETTER O WITH DIAERESIS
    ('\u{004f}', '\u{030b}', '\u{0150}'), // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    ('\u{004f}', '\u{030c}', '\u{01d1}'), // LATIN CAPITAL LETTER O WITH CARON
    ('\u{004f}', '\u{0323}', '\u{1ecc}'), // LATIN CAPITAL LETTER O WITH DOT BELOW
    ('\u{004f}', '\u{0328}', '\u{01ea}'), // LATIN CAPITAL LETTER O WITH OGONEK
    ('\u{0050}', '\u{0301}', '\u{1e54}'), // LATIN CAPITAL LETTER P WITH ACUTE
    ('\u{0050}', '\u{0307}', '\u{1e56}'), // LATIN CAPITAL LETTER P WITH DOT ABOVE
    ('\u{0052}', '\u{0301}', '\u{0154}'), // LATIN CAPITAL LETTER R WITH ACUTE
    ('\u{0052}', '\u{0307}', '\u{1e58}'), // LATIN CAPITAL LETTER R WITH DOT ABOVE
    ('\u{0052}', '\u{030c}', '\u{0158}'), // LATIN CAPITAL LETTER R WITH CARON
    ('\u{0052}', '\u{0323}', '\u{1e5a}'), // LATIN CAPITAL LETTER R WITH DOT BELOW
    ('\u{0052}', '\u{0327}', '\u{0156}'), // LATIN CAPITAL LETTER R WITH CEDILLA
    ('\u{0052}', '\u{0331}', '\u{1e5e}'), // LATIN CAPITAL LETTER R WITH LINE BELOW
    ('\u{0053}', '\u{0301}', '\u{015a}'), // LATIN CAPITAL LETTER S WITH ACUTE
    ('\u{0053}', '\u{0302}', '\u{015c}'), // LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    ('\u{0053}', '\u{0307}', '\u{1e60}'), // LATIN CAPITAL LETTER S WITH DOT ABOVE
    ('\u{0053}', '\u{030c}', '\u{0160}'), // LATIN CAPITAL LETTER S WITH CARON
    ('\u{0053}', '\u{0323}', '\u{1e62}'), // LATIN CAPITAL LETTER S WITH DOT BELOW
    ('\u{0053}', '\u{0327}', '\u{015e}'), // LATIN CAPITAL LETTER S WITH CEDILLA
    ('\u{0054}', '\u{0307}', '\u{1e6a}'), // LATIN CAPITAL LETTER T WITH DOT ABOVE
    ('\u{0054}', '\u{030c}', '\u{0164}'), // LATIN CAPITAL LETTER T WITH CARON
    ('\u{0054}', '\u{0323}', '\u{1e6c}'), // LATIN CAPITAL LETTER T WITH DOT BELOW
    ('\u{0054}', '\u{0327}', '\u{0162}'), // LATIN CAPITAL LETTER T WITH CEDILLA
    ('\u{0054}', '\u{0331}', '\u{1e6e}'), // LATIN CAPITAL LETTER T WITH LINE BELOW
    ('\u{0055}', '\u{0300}', '\u{00d9}'), // LATIN CAPITAL LETTER U WITH GRAVE
    ('\u{0055}', '\u{0301}', '\u{00da}'), // LATIN CAPITAL LETTER U WITH ACUTE
    ('\u{0055}', '\u{0302}', '\u{00db}'), // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    ('\u{0055}', '\u{0303}', '\u{0168}'), // LATIN CAPITAL LETTER U WITH TILDE
    ('\u{0055}', '\u{0304}', '\u{016a}'), // LATIN CAPITAL LETTER U WITH MACRON
    ('\u{0055}', '\u{0306}', '\u{016c}'), // LATIN CAPITAL LETTER U WITH BREVE
    ('\u{0055}', '\u{0308}', '\u{00dc}'), // LATIN CAPITAL LETTER U WITH DIAERESIS
    ('\u{0055}', '\u{030a}', '\u{016e}'), // LATIN CAPITAL LETTER U WITH RING ABOVE
    ('\u{0055}', '\u{030b}', '\u{0170}'), // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    ('\u{0055}', '\u{030c}', '\u{01d3}'), // LATIN CAPITAL LETTER U WITH CARON
    ('\u{0055}', '\u{0323}', '\u{1ee4}'), // LATIN CAPITAL LETTER U WITH DOT BELOW
    ('\u{0055}', '\u{0328}', '\u{0172}'), // LATIN CAPITAL LETTER U WITH OGONEK
    ('\u{0056}', '\u{0303}', '\u{1e7c}'), // LATIN CAPITAL LETTER V WITH TILDE
    ('\u{0056}', '\u{0323}', '\u{1e7e}'), // LATIN CAPITAL LETTER V WITH DOT BELOW
    ('\u{0057}', '\u{0300}', '\u{1e80}'), // LATIN CAPITAL LETTER W WITH GRAVE
    ('\u{0057}', '\u{0301}', '\u{1e82}'), // LATIN CAPITAL LETTER W WITH ACUTE
    ('\u{0057}', '\u{0302}', '\u{0174}'), // LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    ('\u{0057}', '\u{0307}', '\u{1e86}'), // LATIN CAPITAL LETTER W WITH DOT ABOVE
    ('\u{0057}', '\u{0308}', '\u{1e84}'), // LATIN CAPITAL LETTER W WITH DIAERESIS
    ('\u{0057}', '\u{0323}', '\u{1e88}'), // LATIN CAPITAL LETTER W WITH DOT BELOW
    ('\u{0058}', '\u{0307}', '\u{1e8a}'), // LATIN CAPITAL LETTER X WITH DOT ABOVE
    ('\u{0058}', '\u{0308}', '\u{1e8c}'), // LATIN CAPITAL LETTER X WITH DIAERESIS
    ('\u{0059}', '\u{0300}', '\u{1ef2}'), // LATIN CAPITAL LETTER Y WITH GRAVE
    ('\u{0059}', '\u{0301}', '\u{00dd}'), // LATIN CAPITAL LETTER Y WITH ACUTE
    ('\u{0059}', '\u{0302}', '\u{0176}'), // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    ('\u{0059}', '\u{0303}', '\u{1ef8}'), // LATIN CAPITAL LETTER Y WITH TILDE
    ('\u{0059}', '\u{0304}', '\u{0232}'), // LATIN CAPITAL LETTER Y WITH MACRON
    ('\u{0059}', '\u{0307}', '\u{1e8e}'), // LATIN CAPITAL LETTER Y WITH DOT ABOVE
    ('\u{0059}', '\u{0308}', '\u{0178}'), // LATIN CAPITAL LETTER Y WITH DIAERESIS
    ('\u{0059}', '\u{0323}', '\u{1ef4}'), // LATIN CAPITAL LETTER Y WITH DOT BELOW
    ('\u{005a}', '\u{0301}', '\u{0179}'), // LATIN CAPITAL LETTER Z WITH ACUTE
    ('\u{005a}', '\u{0302}', '\u{1e90}'), // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
    ('\u{005a}', '\u{0307}', '\u{017b}'), // LATIN CAPITAL LETTER Z WITH DOT ABOVE
    ('\u{005a}', '\u{030c}', '\u{017d}'), // LATIN CAPITAL LETTER Z WITH CARON
    ('\u{005a}', '\u{0323}', '\u{1e92}'), // LATIN CAPITAL LETTER Z WITH DOT BELOW
    ('\u{005a}', '\u{0331}', '\u{1e94}'), // LATIN CAPITAL LETTER Z WITH LINE BELOW
    ('\u{0061}', '\u{0300}', '\u{00e0}'), // LATIN SMALL LETTER A WITH GRAVE
    ('\u{0061}', '\u{0301}', '\u{00e1}'), // LATIN SMALL LETTER A WITH ACUTE
    ('\u{0061}', '\u{0302}', '\u{00e2}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX
    ('\u{0061}', '\u{0303}', '\u{00e3}'), // LATIN SMALL LETTER A WITH TILDE
    ('\u{0061}', '\u{0304}', '\u{0101}'), // LATIN SMALL LETTER A WITH MACRON
    ('\u{0061}', '\u{0306}', '\u{0103}'), // LATIN SMALL LETTER A WITH BREVE
    ('\u{0061}', '\u{0307}', '\u{0227}'), // LATIN SMALL LETTER A WITH DOT ABOVE
    ('\u{0061}', '\u{0308}', '\u{00e4}'), // LATIN SMALL LETTER A WITH DIAERESIS
    ('\u{0061}', '\u{030a}', '\u{00e5}'), // LATIN SMALL LETTER A WITH RING ABOVE
    ('\u{0061}', '\u{030c}', '\u{01ce}'), // LATIN SMALL LETTER A WITH CARON
    ('\u{0061}', '\u{0323}', '\u{1ea1}'), // LATIN SMALL LETTER A WITH DOT BELOW
    ('\u{0061}', '\u{0328}', '\u{0105}'), // LATIN SMALL LETTER A WITH OGONEK
    ('\u{0062}', '\u{0307}', '\u{1e03}'), // LATIN SMALL LETTER B WITH DOT ABOVE
    ('\u{0062}', '\u{0323}', '\u{1e05}'), // LATIN SMALL LETTER B WITH DOT BELOW
    ('\u{0062}', '\u{0331}', '\u{1e07}'), // LATIN SMALL LETTER B WITH LINE BELOW
    ('\u{0063}', '\u{0301}', '\u{0107}'), // LATIN SMALL LETTER C WITH ACUTE
    ('\u{0063}', '\u{0302}', '\u{0109}'), // LATIN SMALL LETTER C WITH CIRCUMFLEX
    ('\u{0063}', '\u{0307}', '\u{010b}'), // LATIN SMALL LETTER C WITH DOT ABOVE
    ('\u{0063}', '\u{030c}', '\u{010d}'), // LATIN SMALL LETTER C WITH CARON
    ('\u{0063}', '\u{0327}', '\u{00e7}'), // LATIN SMALL LETTER C WITH CEDILLA
    ('\u{0064}', '\u{0307}', '\u{1e0b}'), // LATIN SMALL LETTER D WITH DOT ABOVE
    ('\u{0064}', '\u{030c}', '\u{010f}'), // LATIN SMALL LETTER D WITH CARON
    ('\u{0064}', '\u{0323}', '\u{1e0d}'), // LATIN SMALL LETTER D WITH DOT BELOW
    ('\u{0064}', '\u{0327}', '\u{1e11}'), // LATIN SMALL LETTER D WITH CEDILLA
    ('\u{0064}', '\u{0331}', '\u{1e0f}'), // LATIN SMALL LETTER D WITH LINE BELOW
    ('\u{0065}', '\u{0300}', '\u{00e8}'), // LATIN SMALL LETTER E WITH GRAVE
    ('\u{0065}', '\u{0301}', '\u{00e9}'), // LATIN SMALL LETTER E WITH ACUTE
    ('\u{0065}', '\u{0302}', '\u{00ea}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX
    ('\u{0065}', '\u{0303}', '\u{1ebd}'), // LATIN SMALL LETTER E WITH TILDE
    ('\u{0065}', '\u{0304}', '\u{0113}'), // LATIN SMALL LETTER E WITH MACRON
    ('\u{0065}', '\u{0306}', '\u{0115}'), // LATIN SMALL LETTER E WITH BREVE
    ('\u{0065}', '\u{0307}', '\u{0117}'), // LATIN SMALL LETTER E WITH DOT ABOVE
    ('\u{0065}', '\u{0308}', '\u{00eb}'), // LATIN SMALL LETTER E WITH DIAERESIS
    ('\u{0065}', '\u{030c}', '\u{011b}'), // LATIN SMALL LETTER E WITH CARON
    ('\u{0065}', '\u{0323}', '\u{1eb9}'), // LATIN SMALL LETTER E WITH DOT BELOW
    ('\u{0065}', '\u{0327}', '\u{0229}'), // LATIN SMALL LETTER E WITH CEDILLA
    ('\u{0065}', '\u{0328}', '\u{0119}'), // LATIN SMALL LETTER E WITH OGONEK
    ('\u{0066}', '\u{0307}', '\u{1e1f}'), // LATIN SMALL LETTER F WITH DOT ABOVE
    ('\u{0067}', '\u{0301}', '\u{01f5}'), // LATIN SMALL LETTER G WITH ACUTE
    ('\u{0067}', '\u{0302}', '\u{011d}'), // LATIN SMALL LETTER G WITH CIRCUMFLEX
    ('\u{0067}', '\u{0304}', '\u{1e21}'), // LATIN SMALL LETTER G WITH MACRON
    ('\u{0067}', '\u{0306}', '\u{011f}'), // LATIN SMALL LETTER G WITH BREVE
    ('\u{0067}', '\u{0307}', '\u{0121}'), // LATIN SMALL LETTER G WITH DOT ABOVE
    ('\u{0067}', '\u{030c}', '\u{01e7}'), // LATIN SMALL LETTER G WITH CARON
    ('\u{0067}', '\u{0327}', '\u{0123}'), // LATIN SMALL LETTER G WITH CEDILLA
    ('\u{0068}', '\u{0302}', '\u{0125}'), // LATIN SMALL LETTER H WITH CIRCUMFLEX
    ('\u{0068}', '\u{0307}', '\u{1e23}'), // LATIN SMALL LETTER H WITH DOT ABOVE
    ('\u{0068}', '\u{0308}', '\u{1e27}'), // LATIN SMALL LETTER H WITH DIAERESIS
    ('\u{0068}', '\u{030c}', '\u{021f}'), // LATIN SMALL LETTER H WITH CARON
    ('\u{0068}', '\u{0323}', '\u{1e25}'), // LATIN SMALL LETTER H WITH DOT BELOW
    ('\u{0068}', '\u{0327}', '\u{1e29}'), // LATIN SMALL LETTER H WITH CEDILLA
    ('\u{0068}', '\u{0331}', '\u{1e96}'), // LATIN SMALL LETTER H WITH LINE BELOW
    ('\u{0069}', '\u{0300}', '\u{00ec}'), // LATIN SMALL LETTER I WITH GRAVE
    ('\u{0069}', '\u{0301}', '\u{00ed}'), // LATIN SMALL LETTER I WITH ACUTE
    ('\u{0069}', '\u{0302}', '\u{00ee}'), // LATIN SMALL LETTER I WITH CIRCUMFLEX
    ('\u{0069}', '\u{0303}', '\u{0129}'), // LATIN SMALL LETTER I WITH TILDE
    ('\u{0069}', '\u{0304}', '\u{012b}'), // LATIN SMALL LETTER I WITH MACRON
    ('\u{0069}', '\u{0306}', '\u{012d}'), // LATIN SMALL LETTER I WITH BREVE
    ('\u{0069}', '\u{0308}', '\u{00ef}'), // LATIN SMALL LETTER I WITH DIAERESIS
    ('\u{0069}', '\u{030c}', '\u{01d0}'), // LATIN SMALL LETTER I WITH CARON
    ('\u{0069}', '\u{0323}', '\u{1ecb}'), // LATIN SMALL LETTER I WITH DOT BELOW
    ('\u{0069}', '\u{0328}', '\u{012f}'), // LATIN SMALL LETTER I WITH OGONEK
    ('\u{006a}', '\u{0302}', '\u{0135}'), // LATIN SMALL LETTER J WITH CIRCUMFLEX
    ('\u{006a}', '\u{030c}', '\u{01f0}'), // LATIN SMALL LETTER J WITH CARON
    ('\u{006b}', '\u{0301}', '\u{1e31}'), // LATIN SMALL LETTER K WITH ACUTE
    ('\u{006b}', '\u{030c}', '\u{01e9}'), // LATIN SMALL LETTER K WITH CARON
    ('\u{006b}', '\u{0323}', '\u{1e33}'), // LATIN SMALL LETTER K WITH DOT BELOW
    ('\u{006b}', '\u{0327}', '\u{0137}'), // LATIN SMALL LETTER K WITH CEDILLA
    ('\u{006b}', '\u{0331}', '\u{1e35}'), // LATIN SMALL LETTER K WITH LINE BELOW
    ('\u{006c}', '\u{0301}', '\u{013a}'), // LATIN SMALL LETTER L WITH ACUTE
    ('\u{006c}', '\u{030c}', '\u{013e}'), // LATIN SMALL LETTER L WITH CARON
    ('\u{006c}', '\u{0323}', '\u{1e37}'), // LATIN SMALL LETTER L WITH DOT BELOW
    ('\u{006c}', '\u{0327}', '\u{013c}'), // LATIN SMALL LETTER L WITH CEDILLA
    ('\u{006c}', '\u{0331}', '\u{1e3b}'), // LATIN SMALL LETTER L WITH LINE BELOW
    ('\u{006d}', '\u{0301}', '\u{1e3f}'), // LATIN SMALL LETTER M WITH ACUTE
    ('\u{006d}', '\u{0307}', '\u{1e41}'), // LATIN SMALL LETTER M WITH DOT ABOVE
    ('\u{006d}', '\u{0323}', '\u{1e43}'), // LATIN SMALL LETTER M WITH DOT BELOW
    ('\u{006e}', '\u{0300}', '\u{01f9}'), // LATIN SMALL LETTER N WITH GRAVE
    ('\u{006e}', '\u{0301}', '\u{0144}'), // LATIN SMALL LETTER N WITH ACUTE
    ('\u{006e}', '\u{0303}', '\u{00f1}'), // LATIN SMALL LETTER N WITH TILDE
    ('\u{006e}', '\u{0307}', '\u{1e45}'), // LATIN SMALL LETTER N WITH DOT ABOVE
    ('\u{006e}', '\u{030c}', '\u{0148}'), // LATIN SMALL LETTER N WITH CARON
    ('\u{006e}', '\u{0323}', '\u{1e47}'), // LATIN SMALL LETTER N WITH DOT BELOW
    ('\u{006e}', '\u{0327}', '\u{0146}'), // LATIN SMALL LETTER N WITH CEDILLA
    ('\u{006e}', '\u{0331}', '\u{1e49}'), // LATIN SMALL LETTER N WITH LINE BELOW
    ('\u{006f}', '\u{0300}', '\u{00f2}'), // LATIN SMALL LETTER O WITH GRAVE
    ('\u{006f}', '\u{0301}', '\u{00f3}'), // LATIN SMALL LETTER O WITH ACUTE
    ('\u{006f}', '\u{0302}', '\u{00f4}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX
    ('\u{006f}', '\u{0303}', '\u{00f5}'), // LATIN SMALL LETTER O WITH TILDE
    ('\u{006f}', '\u{0304}', '\u{014d}'), // LATIN SMALL LETTER O WITH MACRON
    ('\u{006f}', '\u{0306}', '\u{014f}'), // LATIN SMALL LETTER O WITH BREVE
    ('\u{006f}', '\u{0307}', '\u{022f}'), // LATIN SMALL LETTER O WITH DOT ABOVE
    ('\u{006f}', '\u{0308}', '\u{00f6}'), // LATIN SMALL LETTER O WITH DIAERESIS
    ('\u{006f}', '\u{030b}', '\u{0151}'), // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    ('\u{006f}', '\u{030c}', '\u{01d2}'), // LATIN SMALL LETTER O WITH CARON
    ('\u{006f}', '\u{0323}', '\u{1ecd}'), // LATIN SMALL LETTER O WITH DOT BELOW
    ('\u{006f}', '\u{0328}', '\u{01eb}'), // LATIN SMALL LETTER O WITH OGONEK
    ('\u{0070}', '\u{0301}', '\u{1e55}'), // LATIN SMALL LETTER P WITH ACUTE
    ('\u{0070}', '\u{0307}', '\u{1e57}'), // LATIN SMALL LETTER P WITH DOT ABOVE
    ('\u{0072}', '\u{0301}', '\u{0155}'), // LATIN SMALL LETTER R WITH ACUTE
    ('\u{0072}', '\u{0307}', '\u{1e59}'), // LATIN SMALL LETTER R WITH DOT ABOVE
    ('\u{0072}', '\u{030c}', '\u{0159}'), // LATIN SMALL LETTER R WITH CARON
    ('\u{0072}', '\u{0323}', '\u{1e5b}'), // LATIN SMALL LETTER R WITH DOT BELOW
    ('\u{0072}', '\u{0327}', '\u{0157}'), // LATIN SMALL LETTER R WITH CEDILLA
    ('\u{0072}', '\u{0331}', '\u{1e5f}'), // LATIN SMALL LETTER R WITH LINE BELOW
    ('\u{0073}', '\u{0301}', '\u{015b}'), // LATIN SMALL LETTER S WITH ACUTE
    ('\u{0073}', '\u{0302}', '\u{015d}'), // LATIN SMALL LETTER S WITH CIRCUMFLEX
    ('\u{0073}', '\u{0307}', '\u{1e61}'), // LATIN SMALL LETTER S WITH DOT ABOVE
    ('\u{0073}', '\u{030c}', '\u{0161}'), // LATIN SMALL LETTER S WITH CARON
    ('\u{0073}', '\u{0323}', '\u{1e63}'), // LATIN SMALL LETTER S WITH DOT BELOW
    ('\u{0073}', '\u{0327}', '\u{015f}'), // LATIN SMALL LETTER S WITH CEDILLA
    ('\u{0074}', '\u{0307}', '\u{1e6b}'), // LATIN SMALL LETTER T WITH DOT ABOVE
    ('\u{0074}', '\u{0308}', '\u{1e97}'), // LATIN SMALL LETTER T WITH DIAERESIS
    ('\u{0074}', '\u{030c}', '\u{0165}'), // LATIN SMALL LETTER T WITH CARON
    ('\u{0074}', '\u{0323}', '\u{1e6d}'), // LATIN SMALL LETTER T WITH DOT BELOW
    ('\u{0074}', '\u{0327}', '\u{0163}'), // LATIN SMALL LETTER T WITH CEDILLA
    ('\u{0074}', '\u{0331}', '\u{1e6f}'), // LATIN SMALL LETTER T WITH LINE BELOW
    ('\u{0075}', '\u{0300}', '\u{00f9}'), // LATIN SMALL LETTER U WITH GRAVE
    ('\u{0075}', '\u{0301}', '\u{00fa}'), // LATIN SMALL LETTER U WITH ACUTE
    ('\u{0075}', '\u{0302}', '\u{00fb}'), // LATIN SMALL LETTER U WITH CIRCUMFLEX
    ('\u{0075}', '\u{0303}', '\u{0169}'), // LATIN SMALL LETTER U WITH TILDE
    ('\u{0075}', '\u{0304}', '\u{016b}'), // LATIN SMALL LETTER U WITH MACRON
    ('\u{0075}', '\u{0306}', '\u{016d}'), // LATIN SMALL LETTER U WITH BREVE
    ('\u{0075}', '\u{0308}', '\u{00fc}'), // LATIN SMALL LETTER U WITH DIAERESIS
    ('\u{0075}', '\u{030a}', '\u{016f}'), // LATIN SMALL LETTER U WITH RING ABOVE
    ('\u{0075}', '\u{030b}', '\u{0171}'), // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    ('\u{0075}', '\u{030c}', '\u{01d4}'), // LATIN SMALL LETTER U WITH CARON
    ('\u{0075}', '\u{0323}', '\u{1ee5}'), // LATIN SMALL LETTER U WITH DOT BELOW
    ('\u{0075}', '\u{0328}', '\u{0173}'), // LATIN SMALL LETTER U WITH OGONEK
    ('\u{0076}', '\u{0303}', '\u{1e7d}'), // LATIN SMALL LETTER V WITH TILDE
    ('\u{0076}', '\u{0323}', '\u{1e7f}'), // LATIN SMALL LETTER V WITH DOT BELOW
    ('\u{0077}', '\u{0300}', '\u{1e81}'), // LATIN SMALL LETTER W WITH GRAVE
    ('\u{0077}', '\u{0301}', '\u{1e83}'), // LATIN SMALL LETTER W WITH ACUTE
    ('\u{0077}', '\u{0302}', '\u{0175}'), // LATIN SMALL LETTER W WITH CIRCUMFLEX
    ('\u{0077}', '\u{0307}', '\u{1e87}'), // LATIN SMALL LETTER W WITH DOT ABOVE
    ('\u{0077}', '\u{0308}', '\u{1e85}'), // LATIN SMALL LETTER W WITH DIAERESIS
    ('\u{0077}', '\u{030a}', '\u{1e98}'), // LATIN SMALL LETTER W WITH RING ABOVE
    ('\u{0077}', '\u{0323}', '\u{1e89}'), // LATIN SMALL LETTER W WITH DOT BELOW
    ('\u{0078}', '\u{0307}', '\u{1e8b}'), // LATIN SMALL LETTER X WITH DOT ABOVE
    ('\u{0078}', '\u{0308}', '\u{1e8d}'), // LATIN SMALL LETTER X WITH DIAERESIS
    ('\u{0079}', '\u{0300}', '\u{1ef3}'), // LATIN SMALL LETTER Y WITH GRAVE
    ('\u{0079}', '\u{0301}', '\u{00fd}'), // LATIN SMALL LETTER Y WITH ACUTE
    ('\u{0079}', '\u{0302}', '\u{0177}'), // LATIN SMALL LETTER Y WITH CIRCUMFLEX
    ('\u{0079}', '\u{0303}', '\u{1ef9}'), // LATIN SMALL LETTER Y WITH TILDE
    ('\u{0079}', '\u{0304}', '\u{0233}'), // LATIN SMALL LETTER Y WITH MACRON
    ('\u{0079}', '\u{0307}', '\u{1e8f}'), // LATIN SMALL LETTER Y WITH DOT ABOVE
    ('\u{0079}', '\u{0308}', '\u{00ff}'), // LATIN SMALL LETTER Y WITH DIAERESIS
    ('\u{0079}', '\u{030a}', '\u{1e99}'), // LATIN SMALL LETTER Y WITH RING ABOVE
    ('\u{0079}', '\u{0323}', '\u{1ef5}'), // LATIN SMALL LETTER Y WITH DOT BELOW
    ('\u{007a}', '\u{0301}', '\u{017a}'), // LATIN SMALL LETTER Z WITH ACUTE
    ('\u{007a}', '\u{0302}', '\u{1e91}'), // LATIN SMALL LETTER Z WITH CIRCUMFLEX
    ('\u{007a}', '\u{0307}', '\u{017c}'), // LATIN SMALL LETTER Z WITH DOT ABOVE
    ('\u{007a}', '\u{030c}', '\u{017e}'), // LATIN SMALL LETTER Z WITH CARON
    ('\u{007a}', '\u{0323}', '\u{1e93}'), // LATIN SMALL LETTER Z WITH DOT BELOW
    ('\u{007a}', '\u{0331}', '\u{1e95}'), // LATIN SMALL LETTER Z WITH LINE BELOW
    ('\u{00a8}', '\u{0300}', '\u{1fed}'), // GREEK DIALYTIKA AND VARIA
    ('\u{00a8}', '\u{0301}', '\u{0385}'), // GREEK DIALYTIKA TONOS
    ('\u{00c2}', '\u{0300}', '\u{1ea6}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
    ('\u{00c2}', '\u{0301}', '\u{1ea4}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
    ('\u{00c2}', '\u{0303}', '\u{1eaa}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
    ('\u{00c2}', '\u{0323}', '\u{1eac}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00c4}', '\u{0304}', '\u{01de}'), // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
    ('\u{00c5}', '\u{0301}', '\u{01fa}'), // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
    ('\u{00c6}', '\u{0301}', '\u{01fc}'), // LATIN CAPITAL LETTER AE WITH ACUTE
    ('\u{00c6}', '\u{0304}', '\u{01e2}'), // LATIN CAPITAL LETTER AE WITH MACRON
    ('\u{00c7}', '\u{0301}', '\u{1e08}'), // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
    ('\u{00ca}', '\u{0300}', '\u{1ec0}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
    ('\u{00ca}', '\u{0301}', '\u{1ebe}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
    ('\u{00ca}', '\u{0303}', '\u{1ec4}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
    ('\u{00ca}', '\u{0323}', '\u{1ec6}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00cf}', '\u{0301}', '\u{1e2e}'), // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
    ('\u{00d4}', '\u{0300}', '\u{1ed2}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
    ('\u{00d4}', '\u{0301}', '\u{1ed0}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
    ('\u{00d4}', '\u{0303}', '\u{1ed6}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
    ('\u{00d4}', '\u{0323}', '\u{1ed8}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00d5}', '\u{0301}', '\u{1e4c}'), // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
    ('\u{00d5}', '\u{0304}', '\u{022c}'), // LATIN CAPITAL LETTER O WITH TILDE AND MACRON
    ('\u{00d5}', '\u{0308}', '\u{1e4e}'), // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
    ('\u{00d6}', '\u{0304}', '\u{022a}'), // LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
    ('\u{00d8}', '\u{0301}', '\u{01fe}'), // LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
    ('\u{00dc}', '\u{0300}', '\u{01db}'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
    ('\u{00dc}', '\u{0301}', '\u{01d7}'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
    ('\u{00dc}', '\u{0304}', '\u{01d5}'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
    ('\u{00dc}', '\u{030c}', '\u{01d9}'), // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
    ('\u{00e2}', '\u{0300}', '\u{1ea7}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
    ('\u{00e2}', '\u{0301}', '\u{1ea5}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
    ('\u{00e2}', '\u{0303}', '\u{1eab}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
    ('\u{00e2}', '\u{0323}', '\u{1ead}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00e4}', '\u{0304}', '\u{01df}'), // LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
    ('\u{00e5}', '\u{0301}', '\u{01fb}'), // LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    ('\u{00e6}', '\u{0301}', '\u{01fd}'), // LATIN SMALL LETTER AE WITH ACUTE
    ('\u{00e6}', '\u{0304}', '\u{01e3}'), // LATIN SMALL LETTER AE WITH MACRON
    ('\u{00e7}', '\u{0301}', '\u{1e09}'), // LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
    ('\u{00ea}', '\u{0300}', '\u{1ec1}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
    ('\u{00ea}', '\u{0301}', '\u{1ebf}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
    ('\u{00ea}', '\u{0303}', '\u{1ec5}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
    ('\u{00ea}', '\u{0323}', '\u{1ec7}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00ef}', '\u{0301}', '\u{1e2f}'), // LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
    ('\u{00f4}', '\u{0300}', '\u{1ed3}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
    ('\u{00f4}', '\u{0301}', '\u{1ed1}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
    ('\u{00f4}', '\u{0303}', '\u{1ed7}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
    ('\u{00f4}', '\u{0323}', '\u{1ed9}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{00f5}', '\u{0301}', '\u{1e4d}'), // LATIN SMALL LETTER O WITH TILDE AND ACUTE
    ('\u{00f5}', '\u{0304}', '\u{022d}'), // LATIN SMALL LETTER O WITH TILDE AND MACRON
    ('\u{00f5}', '\u{0308}', '\u{1e4f}'), // LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
    ('\u{00f6}', '\u{0304}', '\u{022b}'), // LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
    ('\u{00f8}', '\u{0301}', '\u{01ff}'), // LATIN SMALL LETTER O WITH STROKE AND ACUTE
    ('\u{00fc}', '\u{0300}', '\u{01dc}'), // LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
    ('\u{00fc}', '\u{0301}', '\u{01d8}'), // LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
    ('\u{00fc}', '\u{0304}', '\u{01d6}'), // LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
    ('\u{00fc}', '\u{030c}', '\u{01da}'), // LATIN SMALL LETTER U WITH DIAERESIS AND CARON
    ('\u{0102}', '\u{0300}', '\u{1eb0}'), // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
    ('\u{0102}', '\u{0301}', '\u{1eae}'), // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
    ('\u{0102}', '\u{0303}', '\u{1eb4}'), // LATIN CAPITAL LETTER A WITH BREVE AND TILDE
    ('\u{0102}', '\u{0323}', '\u{1eb6}'), // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
    ('\u{0103}', '\u{0300}', '\u{1eb1}'), // LATIN SMALL LETTER A WITH BREVE AND GRAVE
    ('\u{0103}', '\u{0301}', '\u{1eaf}'), // LATIN SMALL LETTER A WITH BREVE AND ACUTE
    ('\u{0103}', '\u{0303}', '\u{1eb5}'), // LATIN SMALL LETTER A WITH BREVE AND TILDE
    ('\u{0103}', '\u{0323}', '\u{1eb7}'), // LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
    ('\u{0106}', '\u{0327}', '\u{1e08}'), // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
    ('\u{0107}', '\u{0327}', '\u{1e09}'), // LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
    ('\u{0112}', '\u{0300}', '\u{1e14}'), // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
    ('\u{0112}', '\u{0301}', '\u{1e16}'), // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
    ('\u{0113}', '\u{0300}', '\u{1e15}'), // LATIN SMALL LETTER E WITH MACRON AND GRAVE
    ('\u{0113}', '\u{0301}', '\u{1e17}'), // LATIN SMALL LETTER E WITH MACRON AND ACUTE
    ('\u{0114}', '\u{0327}', '\u{1e1c}'), // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
    ('\u{0115}', '\u{0327}', '\u{1e1d}'), // LATIN SMALL LETTER E WITH CEDILLA AND BREVE
    ('\u{014c}', '\u{0300}', '\u{1e50}'), // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
    ('\u{014c}', '\u{0301}', '\u{1e52}'), // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
    ('\u{014c}', '\u{0328}', '\u{01ec}'), // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
    ('\u{014d}', '\u{0300}', '\u{1e51}'), // LATIN SMALL LETTER O WITH MACRON AND GRAVE
    ('\u{014d}', '\u{0301}', '\u{1e53}'), // LATIN SMALL LETTER O WITH MACRON AND ACUTE
    ('\u{014d}', '\u{0328}', '\u{01ed}'), // LATIN SMALL LETTER O WITH OGONEK AND MACRON
    ('\u{015a}', '\u{0307}', '\u{1e64}'), // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
    ('\u{015b}', '\u{0307}', '\u{1e65}'), // LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
    ('\u{0160}', '\u{0307}', '\u{1e66}'), // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
    ('\u{0161}', '\u{0307}', '\u{1e67}'), // LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
    ('\u{0168}', '\u{0301}', '\u{1e78}'), // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
    ('\u{0169}', '\u{0301}', '\u{1e79}'), // LATIN SMALL LETTER U WITH TILDE AND ACUTE
    ('\u{016a}', '\u{0308}', '\u{1e7a}'), // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
    ('\u{016b}', '\u{0308}', '\u{1e7b}'), // LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
    ('\u{017f}', '\u{0307}', '\u{1e9b}'), // LATIN SMALL LETTER LONG S WITH DOT ABOVE
    ('\u{01a0}', '\u{0300}', '\u{1edc}'), // LATIN CAPITAL LETTER O WITH HORN AND GRAVE
    ('\u{01a0}', '\u{0301}', '\u{1eda}'), // LATIN CAPITAL LETTER O WITH HORN AND ACUTE
    ('\u{01a0}', '\u{0303}', '\u{1ee0}'), // LATIN CAPITAL LETTER O WITH HORN AND TILDE
    ('\u{01a0}', '\u{0323}', '\u{1ee2}'), // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
    ('\u{01a1}', '\u{0300}', '\u{1edd}'), // LATIN SMALL LETTER O WITH HORN AND GRAVE
    ('\u{01a1}', '\u{0301}', '\u{1edb}'), // LATIN SMALL LETTER O WITH HORN AND ACUTE
    ('\u{01a1}', '\u{0303}', '\u{1ee1}'), // LATIN SMALL LETTER O WITH HORN AND TILDE
    ('\u{01a1}', '\u{0323}', '\u{1ee3}'), // LATIN SMALL LETTER O WITH HORN AND DOT BELOW
    ('\u{01af}', '\u{0300}', '\u{1eea}'), // LATIN CAPITAL LETTER U WITH HORN AND GRAVE
    ('\u{01af}', '\u{0301}', '\u{1ee8}'), // LATIN CAPITAL LETTER U WITH HORN AND ACUTE
    ('\u{01af}', '\u{0303}', '\u{1eee}'), // LATIN CAPITAL LETTER U WITH HORN AND TILDE
    ('\u{01af}', '\u{0323}', '\u{1ef0}'), // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
    ('\u{01b0}', '\u{0300}', '\u{1eeb}'), // LATIN SMALL LETTER U WITH HORN AND GRAVE
    ('\u{01b0}', '\u{0301}', '\u{1ee9}'), // LATIN SMALL LETTER U WITH HORN AND ACUTE
    ('\u{01b0}', '\u{0303}', '\u{1eef}'), // LATIN SMALL LETTER U WITH HORN AND TILDE
    ('\u{01b0}', '\u{0323}', '\u{1ef1}'), // LATIN SMALL LETTER U WITH HORN AND DOT BELOW
    ('\u{01b7}', '\u{030c}', '\u{01ee}'), // LATIN CAPITAL LETTER EZH WITH CARON
    ('\u{01ea}', '\u{0304}', '\u{01ec}'), // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
    ('\u{01eb}', '\u{0304}', '\u{01ed}'), // LATIN SMALL LETTER O WITH OGONEK AND MACRON
    ('\u{0226}', '\u{0304}', '\u{01e0}'), // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
    ('\u{0227}', '\u{0304}', '\u{01e1}'), // LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
    ('\u{0228}', '\u{0306}', '\u{1e1c}'), // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
    ('\u{0229}', '\u{0306}', '\u{1e1d}'), // LATIN SMALL LETTER E WITH CEDILLA AND BREVE
    ('\u{022e}', '\u{0304}', '\u{0230}'), // LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
    ('\u{022f}', '\u{0304}', '\u{0231}'), // LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
    ('\u{0292}', '\u{030c}', '\u{01ef}'), // LATIN SMALL LETTER EZH WITH CARON
    ('\u{0391}', '\u{0300}', '\u{1fba}'), // GREEK CAPITAL LETTER ALPHA WITH VARIA
    ('\u{0391}', '\u{0301}', '\u{0386}'), // GREEK CAPITAL LETTER ALPHA WITH TONOS
    ('\u{0391}', '\u{0304}', '\u{1fb9}'), // GREEK CAPITAL LETTER ALPHA WITH MACRON
    ('\u{0391}', '\u{0306}', '\u{1fb8}'), // GREEK CAPITAL LETTER ALPHA WITH VRACHY
    ('\u{0395}', '\u{0300}', '\u{1fc8}'), // GREEK CAPITAL LETTER EPSILON WITH VARIA
    ('\u{0395}', '\u{0301}', '\u{0388}'), // GREEK CAPITAL LETTER EPSILON WITH TONOS
    ('\u{0397}', '\u{0300}', '\u{1fca}'), // GREEK CAPITAL LETTER ETA WITH VARIA
    ('\u{0397}', '\u{0301}', '\u{0389}'), // GREEK CAPITAL LETTER ETA WITH TONOS
    ('\u{0399}', '\u{0300}', '\u{1fda}'), // GREEK CAPITAL LETTER IOTA WITH VARIA
    ('\u{0399}', '\u{0301}', '\u{038a}'), // GREEK CAPITAL LETTER IOTA WITH TONOS
    ('\u{0399}', '\u{0304}', '\u{1fd9}'), // GREEK CAPITAL LETTER IOTA WITH MACRON
    ('\u{0399}', '\u{0306}', '\u{1fd8}'), // GREEK CAPITAL LETTER IOTA WITH VRACHY
    ('\u{0399}', '\u{0308}', '\u{03aa}'), // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
    ('\u{039f}', '\u{0300}', '\u{1ff8}'), // GREEK CAPITAL LETTER OMICRON WITH VARIA
    ('\u{039f}', '\u{0301}', '\u{038c}'), // GREEK CAPITAL LETTER OMICRON WITH TONOS
    ('\u{03a5}', '\u{0300}', '\u{1fea}'), // GREEK CAPITAL LETTER UPSILON WITH VARIA
    ('\u{03a5}', '\u{0301}', '\u{038e}'), // GREEK CAPITAL LETTER UPSILON WITH TONOS
    ('\u{03a5}', '\u{0304}', '\u{1fe9}'), // GREEK CAPITAL LETTER UPSILON WITH MACRON
    ('\u{03a5}', '\u{0306}', '\u{1fe8}'), // GREEK CAPITAL LETTER UPSILON WITH VRACHY
    ('\u{03a5}', '\u{0308}', '\u{03ab}'), // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
    ('\u{03a9}', '\u{0300}', '\u{1ffa}'), // GREEK CAPITAL LETTER OMEGA WITH VARIA
    ('\u{03a9}', '\u{0301}', '\u{038f}'), // GREEK CAPITAL LETTER OMEGA WITH TONOS
    ('\u{03b1}', '\u{0300}', '\u{1f70}'), // GREEK SMALL LETTER ALPHA WITH VARIA
    ('\u{03b1}', '\u{0301}', '\u{03ac}'), // GREEK SMALL LETTER ALPHA WITH TONOS
    ('\u{03b1}', '\u{0304}', '\u{1fb1}'), // GREEK SMALL LETTER ALPHA WITH MACRON
    ('\u{03b1}', '\u{0306}', '\u{1fb0}'), // GREEK SMALL LETTER ALPHA WITH VRACHY
    ('\u{03b5}', '\u{0300}', '\u{1f72}'), // GREEK SMALL LETTER EPSILON WITH VARIA
    ('\u{03b5}', '\u{0301}', '\u{03ad}'), // GREEK SMALL LETTER EPSILON WITH TONOS
    ('\u{03b7}', '\u{0300}', '\u{1f74}'), // GREEK SMALL LETTER ETA WITH VARIA
    ('\u{03b7}', '\u{0301}', '\u{03ae}'), // GREEK SMALL LETTER ETA WITH TONOS
    ('\u{03b9}', '\u{0300}', '\u{1f76}'), // GREEK SMALL LETTER IOTA WITH VARIA
    ('\u{03b9}', '\u{0301}', '\u{03af}'), // GREEK SMALL LETTER IOTA WITH TONOS
    ('\u{03b9}', '\u{0304}', '\u{1fd1}'), // GREEK SMALL LETTER IOTA WITH MACRON
    ('\u{03b9}', '\u{0306}', '\u{1fd0}'), // GREEK SMALL LETTER IOTA WITH VRACHY
    ('\u{03b9}', '\u{0308}', '\u{03ca}'), // GREEK SMALL LETTER IOTA WITH DIALYTIKA
    ('\u{03bf}', '\u{0300}', '\u{1f78}'), // GREEK SMALL LETTER OMICRON WITH VARIA
    ('\u{03bf}', '\u{0301}', '\u{03cc}'), // GREEK SMALL LETTER OMICRON WITH TONOS
    ('\u{03c5}', '\u{0300}', '\u{1f7a}'), // GREEK SMALL LETTER UPSILON WITH VARIA
    ('\u{03c5}', '\u{0301}', '\u{03cd}'), // GREEK SMALL LETTER UPSILON WITH TONOS
    ('\u{03c5}', '\u{0304}', '\u{1fe1}'), // GREEK SMALL LETTER UPSILON WITH MACRON
    ('\u{03c5}', '\u{0306}', '\u{1fe0}'), // GREEK SMALL LETTER UPSILON WITH VRACHY
    ('\u{03c5}', '\u{0308}', '\u{03cb}'), // GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    ('\u{03c9}', '\u{0300}', '\u{1f7c}'), // GREEK SMALL LETTER OMEGA WITH VARIA
    ('\u{03c9}', '\u{0301}', '\u{03ce}'), // GREEK SMALL LETTER OMEGA WITH TONOS
    ('\u{03ca}', '\u{0300}', '\u{1fd2}'), // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
    ('\u{03ca}', '\u{0301}', '\u{0390}'), // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    ('\u{03cb}', '\u{0300}', '\u{1fe2}'), // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
    ('\u{03cb}', '\u{0301}', '\u{03b0}'), // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
    ('\u{03d2}', '\u{0301}', '\u{03d3}'), // GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
    ('\u{03d2}', '\u{0308}', '\u{03d4}'), // GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
    ('\u{0406}', '\u{0308}', '\u{0407}'), // CYRILLIC CAPITAL LETTER YI
    ('\u{0410}', '\u{0306}', '\u{04d0}'), // CYRILLIC CAPITAL LETTER A WITH BREVE
    ('\u{0410}', '\u{0308}', '\u{04d2}'), // CYRILLIC CAPITAL LETTER A WITH DIAERESIS
    ('\u{0413}', '\u{0301}', '\u{0403}'), // CYRILLIC CAPITAL LETTER GJE
    ('\u{0415}', '\u{0300}', '\u{0400}'), // CYRILLIC CAPITAL LETTER IE WITH GRAVE
    ('\u{0415}', '\u{0306}', '\u{04d6}'), // CYRILLIC CAPITAL LETTER IE WITH BREVE
    ('\u{0415}', '\u{0308}', '\u{0401}'), // CYRILLIC CAPITAL LETTER IO
    ('\u{0416}', '\u{0306}', '\u{04c1}'), // CYRILLIC CAPITAL LETTER ZHE WITH BREVE
    ('\u{0416}', '\u{0308}', '\u{04dc}'), // CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
    ('\u{0417}', '\u{0308}', '\u{04de}'), // CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
    ('\u{0418}', '\u{0300}', '\u{040d}'), // CYRILLIC CAPITAL LETTER I WITH GRAVE
    ('\u{0418}', '\u{0304}', '\u{04e2}'), // CYRILLIC CAPITAL LETTER I WITH MACRON
    ('\u{0418}', '\u{0306}', '\u{0419}'), // CYRILLIC CAPITAL LETTER SHORT I
    ('\u{0418}', '\u{0308}', '\u{04e4}'), // CYRILLIC CAPITAL LETTER I WITH DIAERESIS
    ('\u{041a}', '\u{0301}', '\u{040c}'), // CYRILLIC CAPITAL LETTER KJE
    ('\u{041e}', '\u{0308}', '\u{04e6}'), // CYRILLIC CAPITAL LETTER O WITH DIAERESIS
    ('\u{0423}', '\u{0304}', '\u{04ee}'), // CYRILLIC CAPITAL LETTER U WITH MACRON
    ('\u{0423}', '\u{0306}', '\u{040e}'), // CYRILLIC CAPITAL LETTER SHORT U
    ('\u{0423}', '\u{0308}', '\u{04f0}'), // CYRILLIC CAPITAL LETTER U WITH DIAERESIS
    ('\u{0423}', '\u{030b}', '\u{04f2}'), // CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
    ('\u{0427}', '\u{0308}', '\u{04f4}'), // CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
    ('\u{042b}', '\u{0308}', '\u{04f8}'), // CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
    ('\u{042d}', '\u{0308}', '\u{04ec}'), // CYRILLIC CAPITAL LETTER E WITH DIAERESIS
    ('\u{0430}', '\u{0306}', '\u{04d1}'), // CYRILLIC SMALL LETTER A WITH BREVE
    ('\u{0430}', '\u{0308}', '\u{04d3}'), // CYRILLIC SMALL LETTER A WITH DIAERESIS
    ('\u{0433}', '\u{0301}', '\u{0453}'), // CYRILLIC SMALL LETTER GJE
    ('\u{0435}', '\u{0300}', '\u{0450}'), // CYRILLIC SMALL LETTER IE WITH GRAVE
    ('\u{0435}', '\u{0306}', '\u{04d7}'), // CYRILLIC SMALL LETTER IE WITH BREVE
    ('\u{0435}', '\u{0308}', '\u{0451}'), // CYRILLIC SMALL LETTER IO
    ('\u{0436}', '\u{0306}', '\u{04c2}'), // CYRILLIC SMALL LETTER ZHE WITH BREVE
    ('\u{0436}', '\u{0308}', '\u{04dd}'), // CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
    ('\u{0437}', '\u{0308}', '\u{04df}'), // CYRILLIC SMALL LETTER ZE WITH DIAERESIS
    ('\u{0438}', '\u{0300}', '\u{045d}'), // CYRILLIC SMALL LETTER I WITH GRAVE
    ('\u{0438}', '\u{0304}', '\u{04e3}'), // CYRILLIC SMALL LETTER I WITH MACRON
    ('\u{0438}', '\u{0306}', '\u{0439}'), // CYRILLIC SMALL LETTER SHORT I
    ('\u{0438}', '\u{0308}', '\u{04e5}'), // CYRILLIC SMALL LETTER I WITH DIAERESIS
    ('\u{043a}', '\u{0301}', '\u{045c}'), // CYRILLIC SMALL LETTER KJE
    ('\u{043e}', '\u{0308}', '\u{04e7}'), // CYRILLIC SMALL LETTER O WITH DIAERESIS
    ('\u{0443}', '\u{0304}', '\u{04ef}'), // CYRILLIC SMALL LETTER U WITH MACRON
    ('\u{0443}', '\u{0306}', '\u{045e}'), // CYRILLIC SMALL LETTER SHORT U
    ('\u{0443}', '\u{0308}', '\u{04f1}'), // CYRILLIC SMALL LETTER U WITH DIAERESIS
    ('\u{0443}', '\u{030b}', '\u{04f3}'), // CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
    ('\u{0447}', '\u{0308}', '\u{04f5}'), // CYRILLIC SMALL LETTER CHE WITH DIAERESIS
    ('\u{044b}', '\u{0308}', '\u{04f9}'), // CYRILLIC SMALL LETTER YERU WITH DIAERESIS
    ('\u{044d}', '\u{0308}', '\u{04ed}'), // CYRILLIC SMALL LETTER E WITH DIAERESIS
    ('\u{0456}', '\u{0308}', '\u{0457}'), // CYRILLIC SMALL LETTER YI
    ('\u{04d8}', '\u{0308}', '\u{04da}'), // CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
    ('\u{04d9}', '\u{0308}', '\u{04db}'), // CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
    ('\u{04e8}', '\u{0308}', '\u{04ea}'), // CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
    ('\u{04e9}', '\u{0308}', '\u{04eb}'), // CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
    ('\u{1e36}', '\u{0304}', '\u{1e38}'), // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
    ('\u{1e37}', '\u{0304}', '\u{1e39}'), // LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
    ('\u{1e5a}', '\u{0304}', '\u{1e5c}'), // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
    ('\u{1e5b}', '\u{0304}', '\u{1e5d}'), // LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
    ('\u{1e60}', '\u{0323}', '\u{1e68}'), // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1e61}', '\u{0323}', '\u{1e69}'), // LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1e62}', '\u{0307}', '\u{1e68}'), // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1e63}', '\u{0307}', '\u{1e69}'), // LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
    ('\u{1ea0}', '\u{0302}', '\u{1eac}'), // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1ea0}', '\u{0306}', '\u{1eb6}'), // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
    ('\u{1ea1}', '\u{0302}', '\u{1ead}'), // LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1ea1}', '\u{0306}', '\u{1eb7}'), // LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
    ('\u{1eb8}', '\u{0302}', '\u{1ec6}'), // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1eb9}', '\u{0302}', '\u{1ec7}'), // LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1ecc}', '\u{0302}', '\u{1ed8}'), // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1ecd}', '\u{0302}', '\u{1ed9}'), // LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    ('\u{1f00}', '\u{0300}', '\u{1f02}'), // GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
    ('\u{1f00}', '\u{0301}', '\u{1f04}'), // GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
    ('\u{1f01}', '\u{0300}', '\u{1f03}'), // GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
    ('\u{1f01}', '\u{0301}', '\u{1f05}'), // GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
    ('\u{1f08}', '\u{0300}', '\u{1f0a}'), // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
    ('\u{1f08}', '\u{0301}', '\u{1f0c}'), // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
    ('\u{1f09}', '\u{0300}', '\u{1f0b}'), // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
    ('\u{1f09}', '\u{0301}', '\u{1f0d}'), // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
    ('\u{1f10}', '\u{0300}', '\u{1f12}'), // GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
    ('\u{1f10}', '\u{0301}', '\u{1f14}'), // GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
    ('\u{1f11}', '\u{0300}', '\u{1f13}'), // GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
    ('\u{1f11}', '\u{0301}', '\u{1f15}'), // GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
    ('\u{1f18}', '\u{0300}', '\u{1f1a}'), // GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
    ('\u{1f18}', '\u{0301}', '\u{1f1c}'), // GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
    ('\u{1f19}', '\u{0300}', '\u{1f1b}'), // GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
    ('\u{1f19}', '\u{0301}', '\u{1f1d}'), // GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
    ('\u{1f20}', '\u{0300}', '\u{1f22}'), // GREEK SMALL LETTER ETA WITH PSILI AND VARIA
    ('\u{1f20}', '\u{0301}', '\u{1f24}'), // GREEK SMALL LETTER ETA WITH PSILI AND OXIA
    ('\u{1f21}', '\u{0300}', '\u{1f23}'), // GREEK SMALL LETTER ETA WITH DASIA AND VARIA
    ('\u{1f21}', '\u{0301}', '\u{1f25}'), // GREEK SMALL LETTER ETA WITH DASIA AND OXIA
    ('\u{1f28}', '\u{0300}', '\u{1f2a}'), // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
    ('\u{1f28}', '\u{0301}', '\u{1f2c}'), // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
    ('\u{1f29}', '\u{0300}', '\u{1f2b}'), // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
    ('\u{1f29}', '\u{0301}', '\u{1f2d}'), // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
    ('\u{1f30}', '\u{0300}', '\u{1f32}'), // GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
    ('\u{1f30}', '\u{0301}', '\u{1f34}'), // GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
    ('\u{1f31}', '\u{0300}', '\u{1f33}'), // GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
    ('\u{1f31}', '\u{0301}', '\u{1f35}'), // GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
    ('\u{1f38}', '\u{0300}', '\u{1f3a}'), // GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
    ('\u{1f38}', '\u{0301}', '\u{1f3c}'), // GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
    ('\u{1f39}', '\u{0300}', '\u{1f3b}'), // GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
    ('\u{1f39}', '\u{0301}', '\u{1f3d}'), // GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
    ('\u{1f40}', '\u{0300}', '\u{1f42}'), // GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
    ('\u{1f40}', '\u{0301}', '\u{1f44}'), // GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
    ('\u{1f41}', '\u{0300}', '\u{1f43}'), // GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
    ('\u{1f41}', '\u{0301}', '\u{1f45}'), // GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
    ('\u{1f48}', '\u{0300}', '\u{1f4a}'), // GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
    ('\u{1f48}', '\u{0301}', '\u{1f4c}'), // GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
    ('\u{1f49}', '\u{0300}', '\u{1f4b}'), // GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
    ('\u{1f49}', '\u{0301}', '\u{1f4d}'), // GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
    ('\u{1f50}', '\u{0300}', '\u{1f52}'), // GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
    ('\u{1f50}', '\u{0301}', '\u{1f54}'), // GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
    ('\u{1f51}', '\u{0300}', '\u{1f53}'), // GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
    ('\u{1f51}', '\u{0301}', '\u{1f55}'), // GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
    ('\u{1f59}', '\u{0300}', '\u{1f5b}'), // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
    ('\u{1f59}', '\u{0301}', '\u{1f5d}'), // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
    ('\u{1f60}', '\u{0300}', '\u{1f62}'), // GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
    ('\u{1f60}', '\u{0301}', '\u{1f64}'), // GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
    ('\u{1f61}', '\u{0300}', '\u{1f63}'), // GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
    ('\u{1f61}', '\u{0301}', '\u{1f65}'), // GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
    ('\u{1f68}', '\u{0300}', '\u{1f6a}'), // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
    ('\u{1f68}', '\u{0301}', '\u{1f6c}'), // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
    ('\u{1f69}', '\u{0300}', '\u{1f6b}'), // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
    ('\u{1f69}', '\u{0301}', '\u{1f6d}'), // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
    ('\u{1f80}', '\u{0300}', '\u{1f82}'), // GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    ('\u{1f80}', '\u{0301}', '\u{1f84}'), // GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    ('\u{1f81}', '\u{0300}', '\u{1f83}'), // GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    ('\u{1f81}', '\u{0301}', '\u{1f85}'), // GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    ('\u{1f88}', '\u{0300}', '\u{1f8a}'), // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    ('\u{1f88}', '\u{0301}', '\u{1f8c}'), // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    ('\u{1f89}', '\u{0300}', '\u{1f8b}'), // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    ('\u{1f89}', '\u{0301}', '\u{1f8d}'), // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    ('\u{1f90}', '\u{0300}', '\u{1f92}'), // GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    ('\u{1f90}', '\u{0301}', '\u{1f94}'), // GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    ('\u{1f91}', '\u{0300}', '\u{1f93}'), // GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    ('\u{1f91}', '\u{0301}', '\u{1f95}'), // GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    ('\u{1f98}', '\u{0300}', '\u{1f9a}'), // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    ('\u{1f98}', '\u{0301}', '\u{1f9c}'), // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    ('\u{1f99}', '\u{0300}', '\u{1f9b}'), // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    ('\u{1f99}', '\u{0301}', '\u{1f9d}'), // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    ('\u{1fa0}', '\u{0300}', '\u{1fa2}'), // GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
    ('\u{1fa0}', '\u{0301}', '\u{1fa4}'), // GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
    ('\u{1fa1}', '\u{0300}', '\u{1fa3}'), // GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
    ('\u{1fa1}', '\u{0301}', '\u{1fa5}'), // GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
    ('\u{1fa8}', '\u{0300}', '\u{1faa}'), // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
    ('\u{1fa8}', '\u{0301}', '\u{1fac}'), // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
    ('\u{1fa9}', '\u{0300}', '\u{1fab}'), // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
    ('\u{1fa9}', '\u{0301}', '\u{1fad}'), // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
    ('\u{1fb3}', '\u{0300}', '\u{1fb2}'), // GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
    ('\u{1fb3}', '\u{0301}', '\u{1fb4}'), // GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
    ('\u{1fbe}', '\u{0300}', '\u{1f76}'), // GREEK SMALL LETTER IOTA WITH VARIA
    ('\u{1fbe}', '\u{0301}', '\u{03af}'), // GREEK SMALL LETTER IOTA WITH TONOS
    ('\u{1fbe}', '\u{0304}', '\u{1fd1}'), // GREEK SMALL LETTER IOTA WITH MACRON
    ('\u{1fbe}', '\u{0306}', '\u{1fd0}'), // GREEK SMALL LETTER IOTA WITH VRACHY
    ('\u{1fbe}', '\u{0308}', '\u{03ca}'), // GREEK SMALL LETTER IOTA WITH DIALYTIKA
    ('\u{1fbf}', '\u{0300}', '\u{1fcd}'), // GREEK PSILI AND VARIA
    ('\u{1fbf}', '\u{0301}', '\u{1fce}'), // GREEK PSILI AND OXIA
    ('\u{1fc3}', '\u{0300}', '\u{1fc2}'), // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
    ('\u{1fc3}', '\u{0301}', '\u{1fc4}'), // GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
    ('\u{1ff3}', '\u{0300}', '\u{1ff2}'), // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
    ('\u{1ff3}', '\u{0301}', '\u{1ff4}'), // GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
    ('\u{1ffe}', '\u{0300}', '\u{1fdd}'), // GREEK DASIA AND VARIA
    ('\u{1ffe}', '\u{0301}', '\u{1fde}'), // GREEK DASIA AND OXIA
    ('\u{2190}', '\u{0338}', '\u{219a}'), // LEFTWARDS ARROW WITH STROKE
    ('\u{2192}', '\u{0338}', '\u{219b}'), // RIGHTWARDS ARROW WITH STROKE
    ('\u{2194}', '\u{0338}', '\u{21ae}'), // LEFT RIGHT ARROW WITH STROKE
    ('\u{21d0}', '\u{0338}', '\u{21cd}'), // LEFTWARDS DOUBLE ARROW WITH STROKE
    ('\u{21d2}', '\u{0338}', '\u{21cf}'), // RIGHTWARDS DOUBLE ARROW WITH STROKE
    ('\u{21d4}', '\u{0338}', '\u{21ce}'), // LEFT RIGHT DOUBLE ARROW WITH STROKE
    ('\u{2203}', '\u{0338}', '\u{2204}'), // THERE DOES NOT EXIST
    ('\u{2208}', '\u{0338}', '\u{2209}'), // NOT AN ELEMENT OF
    ('\u{220b}', '\u{0338}', '\u{220c}'), // DOES NOT CONTAIN AS MEMBER
    ('\u{2223}', '\u{0338}', '\u{2224}'), // DOES NOT DIVIDE
    ('\u{2225}', '\u{0338}', '\u{2226}'), // NOT PARALLEL TO
    ('\u{223c}', '\u{0338}', '\u{2241}'), // NOT TILDE
    ('\u{2243}', '\u{0338}', '\u{2244}'), // NOT ASYMPTOTICALLY EQUAL TO
    ('\u{2245}', '\u{0338}', '\u{2247}'), // NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
    ('\u{2248}', '\u{0338}', '\u{2249}'), // NOT ALMOST EQUAL TO
    ('\u{224d}', '\u{0338}', '\u{226d}'), // NOT EQUIVALENT TO
    ('\u{2261}', '\u{0338}', '\u{2262}'), // NOT IDENTICAL TO
    ('\u{2264}', '\u{0338}', '\u{2270}'), // NEITHER LESS-THAN NOR EQUAL TO
    ('\u{2265}', '\u{0338}', '\u{2271}'), // NEITHER GREATER-THAN NOR EQUAL TO
    ('\u{2272}', '\u{0338}', '\u{2274}'), // NEITHER LESS-THAN NOR EQUIVALENT TO
    ('\u{2273}', '\u{0338}', '\u{2275}'), // NEITHER GREATER-THAN NOR EQUIVALENT TO
    ('\u{2276}', '\u{0338}', '\u{2278}'), // NEITHER LESS-THAN NOR GREATER-THAN
    ('\u{2277}', '\u{0338}', '\u{2279}'), // NEITHER GREATER-THAN NOR LESS-THAN
    ('\u{227a}', '\u{0338}', '\u{2280}'), // DOES NOT PRECEDE
    ('\u{227b}', '\u{0338}', '\u{2281}'), // DOES NOT SUCCEED
    ('\u{227c}', '\u{0338}', '\u{22e0}'), // DOES NOT PRECEDE OR EQUAL
    ('\u{227d}', '\u{0338}', '\u{22e1}'), // DOES NOT SUCCEED OR EQUAL
    ('\u{2282}', '\u{0338}', '\u{2284}'), // NOT A SUBSET OF
    ('\u{2283}', '\u{0338}', '\u{2285}'), // NOT A SUPERSET OF
    ('\u{2286}', '\u{0338}', '\u{2288}'), // NEITHER A SUBSET OF NOR EQUAL TO
    ('\u{2287}', '\u{0338}', '\u{2289}'), // NEITHER A SUPERSET OF NOR EQUAL TO
    ('\u{2291}', '\u{0338}', '\u{22e2}'), // NOT SQUARE IMAGE OF OR EQUAL TO
    ('\u{2292}', '\u{0338}', '\u{22e3}'), // NOT SQUARE ORIGINAL OF OR EQUAL TO
    ('\u{22a2}', '\u{0338}', '\u{22ac}'), // DOES NOT PROVE
    ('\u{22a8}', '\u{0338}', '\u{22ad}'), // NOT TRUE
    ('\u{22a9}', '\u{0338}', '\u{22ae}'), // DOES NOT FORCE
    ('\u{22ab}', '\u{0338}', '\u{22af}'), // NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
    ('\u{22b2}', '\u{0338}', '\u{22ea}'), // NOT NORMAL SUBGROUP OF
    ('\u{22b3}', '\u{0338}', '\u{22eb}'), // DOES NOT CONTAIN AS NORMAL SUBGROUP
    ('\u{22b4}', '\u{0338}', '\u{22ec}'), // NOT NORMAL SUBGROUP OF OR EQUAL TO
    ('\u{22b5}', '\u{0338}', '\u{22ed}'), // DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
];
