//! The generated long tail of symbol definitions (PLAN.md §12.1, §12.3, §12.4).
//!
//! About a thousand macros: everything pylatexenc's two default-spec tables know, ported
//! mechanically. Roughly half of it is the tail no curated category of this library
//! bothers with — the Cyrillic transliteration names, the planet and zodiac signs, the
//! several hundred mathematical relations and arrows nobody writes by hand but every
//! third paper contains one of — and the other half is names a curated category also
//! defines, better. This category is pushed **first** of all of them precisely so that
//! every curated definition after it wins (PLAN.md §12.1); carrying the overlap costs
//! nothing and means the table can be regenerated without re-deriving what to leave out.
//!
//! # It is data, not code
//!
//! The table itself is generated by `tools/gen_symbols.py` from a pylatexenc checkout
//! and committed as `symbols_extra_data.rs`; this module is only the four-line loop
//! that turns each row into a [`MacroDef`]. Do not edit the data file — regenerate it.
//!
//! Each row says four things:
//!
//! | column | meaning |
//! |---|---|
//! | name | the macro's name, without its escape character |
//! | rule | what it renders as: nothing, fixed text, or a [`Template`] over its arguments |
//! | arguments | the arguments it declares, as `(techy code, name)` pairs |
//! | mode | text mode, math mode, or both |
//!
//! # Why the modes matter
//!
//! `\alpha` is a math command and `\textbullet` a text one. pylatexenc's tables record
//! that nowhere, so the generator reconstructs it — chiefly from which commands
//! `latexencode` has to wrap in `\ensuremath` to paste into running text. Where the
//! evidence runs out an entry is registered in both modes, which is what pylatexenc
//! does with all of them.
//!
//! Two things are worth knowing about what a restriction actually buys.
//!
//! An entry that **declares arguments is never restricted**. A mode-invisible macro
//! does not simply vanish: with the catch-all fallback registered — the default under
//! [`Recovery::Tolerant`](techy::error::Recovery) — it resolves to a *zero-argument*
//! spec instead, so its arguments are read as ordinary groups and rendered.
//! `$\textcolor{red}{x}$` under a text-only `\textcolor` would print "redx". A
//! restriction is only safe on an entry with nothing to leak.
//!
//! And a restriction is a **parse-side** gate. When a rule-less callable does reach the
//! renderer, its rule is looked up by name (PLAN.md §10.3 step 3) from a table that
//! does not record modes, because that table exists to work on trees parsed by someone
//! else's definitions. So with the catch-all registered, `\lessapprox` in a paragraph
//! still renders `⪅`; it is under
//! [`UnknownMacroResolution::Reject`](crate::convert::UnknownMacroResolution::Reject)
//! (or [`Recovery::Strict`](techy::error::Recovery)) that the mode restriction shows.
//!
//! # Replacement text is never styled
//!
//! Every replacement here reaches the renderer as a [`TextRule::Literal`] or a
//! [`TextRule::Template`], and rule output is exempt from the font alphabets
//! (DECISIONS.md D6). That is why `\hbar` stays `ℏ` inside a `\mathbf{…}` instead of
//! being mapped through the bold alphabet and lost.

use alloc::borrow::Cow;

use crate::def::{Category, MacroDef, Template, TextRule};

#[path = "symbols_extra_data.rs"]
mod data;

/// One row of the generated table: name, rule, declared arguments, modes.
///
/// A tuple rather than a struct because the generated file is meant to be *read*: a
/// thousand rows of `("alpha", Literal("α"), &[], Math),` show the shape of the table
/// at a glance, where a thousand braced struct literals would not.
type Symbol = (
    &'static str,
    SymbolRule,
    &'static [(&'static str, &'static str)],
    SymbolMode,
);

/// What a generated entry renders as.
///
/// The three shapes PLAN.md §12.3 allows a ported v3 `simplify_repl` to take. It is a
/// narrower type than [`TextRule`] on purpose: a generated entry can never carry a
/// handler, so the data file cannot smuggle behavior past review.
enum SymbolRule {
    /// Renders as nothing; the arguments are still parsed, and so cannot leak.
    Skip,
    /// Renders as fixed text.
    Literal(&'static str),
    /// Renders through a template over the entry's arguments (PLAN.md §10.5).
    Template(&'static str),
}

/// Which modes a generated entry is visible in.
enum SymbolMode {
    /// Both modes — where the evidence is inconclusive, and always where the entry
    /// declares arguments.
    Any,
    /// Math mode only: `\alpha`, `\leq`, `\otimes`.
    Math,
    /// Text mode only: the `\text…` symbols, the accents, `\ss` and friends.
    Text,
}

/// The symbols_extra category (PLAN.md §12.1).
///
/// ```
/// use techxt::Converter;
///
/// let converter = Converter::standard();
/// // A math relation nothing else in the library defines.
/// assert_eq!(converter.latex_to_text(r"$a \triangleq b$")?.text, "𝑎 ≜ 𝑏\n");
/// // A text symbol, likewise.
/// assert_eq!(converter.latex_to_text(r"\textreferencemark")?.text, "※\n");
/// # Ok::<(), Box<dyn core::error::Error>>(())
/// ```
pub fn category() -> Category {
    let mut category = Category::new("symbols_extra");
    for (name, rule, arguments, mode) in data::SYMBOLS {
        let mut definition = MacroDef::new(*name);
        for (code, argument) in *arguments {
            definition = definition.arg(code, argument);
        }
        definition = definition.rule(match rule {
            SymbolRule::Skip => TextRule::Skip,
            // Borrowed, not owned: the replacement is already a `'static` string, and
            // a thousand needless allocations per converter is a thousand too many.
            SymbolRule::Literal(text) => TextRule::Literal(Cow::Borrowed(text)),
            SymbolRule::Template(source) => TextRule::Template(Template::new(*source)),
        });
        category.add_macro(match mode {
            SymbolMode::Any => definition,
            SymbolMode::Math => definition.math_mode_only(),
            SymbolMode::Text => definition.text_mode_only(),
        });
    }
    category
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::collections::BTreeSet;

    /// The size of the generated table, as `tools/gen_symbols.py` produced it.
    ///
    /// Pinned so that a regeneration that quietly loses (or doubles) a table shows up
    /// as a failing test rather than as a symbol that stopped converting.
    const GENERATED_ENTRIES: usize = 991;

    #[test]
    fn the_table_is_the_size_it_was_generated_at() {
        assert_eq!(data::SYMBOLS.len(), GENERATED_ENTRIES);
    }

    #[test]
    fn the_table_is_sorted_by_name() {
        let mut previous = "";
        for (name, ..) in data::SYMBOLS {
            assert!(
                previous < name,
                "{previous:?} is not before {name:?}: the table must be sorted and \
                 duplicate-free so that it can be read and diffed"
            );
            previous = name;
        }
    }

    #[test]
    fn no_name_is_defined_twice() {
        let unique: BTreeSet<&str> = data::SYMBOLS.iter().map(|(name, ..)| *name).collect();
        assert_eq!(unique.len(), data::SYMBOLS.len());
    }

    #[test]
    fn every_argument_is_named_and_named_once() {
        for (name, _, arguments, _) in data::SYMBOLS {
            let unique: BTreeSet<&str> = arguments.iter().map(|(_, arg)| *arg).collect();
            assert_eq!(
                unique.len(),
                arguments.len(),
                "\\{name} names an argument twice"
            );
            assert!(
                arguments.iter().all(|(_, arg)| !arg.is_empty()),
                "\\{name} has an unnamed argument"
            );
        }
    }

    #[test]
    fn every_template_compiles() {
        for (name, rule, ..) in data::SYMBOLS {
            if let SymbolRule::Template(source) = rule {
                assert!(
                    Template::new(*source).error().is_none(),
                    "\\{name}'s template {source:?} does not compile"
                );
            }
        }
    }

    #[test]
    fn the_category_holds_the_whole_table() {
        // `Category` does not expose its entries, so the count is checked the only way
        // a category ever is: by building it and asking whether it built.
        let category = category();
        assert_eq!(category.name(), "symbols_extra");
    }
}
