//! The generated long tail of symbol definitions (PLAN.md §12.1, §12.4).
//!
//! About a thousand argument-less macros: the symbols pylatexenc's tables know that no
//! other category curates. It is pushed **first** of all the categories, so that every
//! curated definition after it can correct an entry.

use crate::def::Category;

/// The symbols_extra category (PLAN.md §12.1).
///
/// **TODO(M8): a stub — this category is empty.** It is to be generated by
/// `tools/gen_symbols.py`, which already reads pylatexenc and emits checked-in Rust for
/// the accent tables; the long tail is the same mechanism applied to pylatexenc's
/// symbol lists, with the curated categories' entries excluded.
pub fn category() -> Category {
    Category::new("symbols_extra")
}
