#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate techxt's checked-in symbol tables from a pylatexenc checkout.

This is a **development aid**, not part of the cargo build: it is run by hand when
the upstream tables change, and its output is committed alongside it.  Re-running
it must produce byte-identical files unless the inputs changed (PLAN.md §12.4).

Usage::

    tools/gen_symbols.py /path/to/pylatexenc [--out rust/techxt/src]
    tools/gen_symbols.py /path/to/pylatexenc --check   # regenerate and diff

What it generates today (milestone M4):

``defs/accents_data.rs``
    the accent table of PLAN.md §9.3 — the LaTeX accent macros and the combining
    character each installs, ported from pylatexenc's ``unicode_accents_list`` —
    plus the two unicode-derived tables the plan's accent rule needs: the spacing
    clone of every combining character (for ``\\'{}`` with an empty argument) and
    the (base, combining) pairs that compose to a precomposed character under NFC.

The composition and spacing tables are derived from the Python runtime's own
unicode database rather than transcribed, because they are pure unicode facts:
what ``NFC`` does with a pair, and which spacing character is the standalone clone
of a combining mark.  pylatexenc calls ``unicodedata.normalize`` at run time for
exactly this; techxt is ``no_std`` and has no unicode database, so the answer is
precomputed here instead.

Adding a generator (milestone M8's ``symbols_extra``, the ~1000-entry long tail):
write a ``generate_<name>(pylatexenc)`` function returning the file body, and add
it to ``GENERATORS``.  The pylatexenc reading helpers, the deduplicate-and-sort
rule and the file writer are shared and need no change.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import re
import sys
import unicodedata
from pathlib import Path

HEADER = "// GENERATED by tools/gen_symbols.py — do not edit"

# Bases scanned when looking for (base, combining) pairs that compose.  The range
# covers every script a LaTeX accent macro can plausibly be applied to — latin and
# its two extended blocks, IPA, greek (incl. Greek Extended) and cyrillic — and
# stops well before the CJK blocks, which no combining accent composes with.  It
# also sweeps the arrow and mathematical-operator blocks, whose members compose
# with the negation overlay of ``\not``.
COMPOSITION_BASE_RANGES = ((0x0020, 0x2100), (0x2190, 0x2300))


# --------------------------------------------------------------- reading pylatexenc


def read_literal(source: Path, name: str):
    """Evaluate the top-level literal assigned to ``name`` in a Python source file.

    Reading the literal out of the file — rather than importing pylatexenc — keeps
    this script free of any dependency on pylatexenc being installed or importable,
    and makes it obvious in a diff which upstream text a regenerated table came
    from.  Only literal assignments can be read this way, which is what
    pylatexenc's symbol tables are.
    """
    text = source.read_text(encoding="utf-8")
    match = re.search(rf"^{re.escape(name)}\s*=\s*", text, re.MULTILINE)
    if match is None:
        raise SystemExit(f"{source}: no assignment to {name!r} found")
    # `ast.parse` needs a complete statement; feed it the rest of the file and take
    # the first one, which is the assignment just located.
    module = ast.parse(text[match.start():])
    statement = module.body[0]
    if not isinstance(statement, ast.Assign):
        raise SystemExit(f"{source}: {name!r} is not a plain assignment")
    try:
        return ast.literal_eval(statement.value)
    except ValueError as error:
        raise SystemExit(f"{source}: {name!r} is not a literal: {error}") from error


def dedup_sorted(entries, key=lambda entry: entry[0]):
    """Deduplicate by ``key`` keeping the **last** occurrence, then sort by it.

    Last wins because that is how pylatexenc's own tables read: a later entry in a
    spec list overrides an earlier one of the same name.
    """
    latest = {}
    for entry in entries:
        latest[key(entry)] = entry
    return [latest[k] for k in sorted(latest)]


# ------------------------------------------------------------------ rust emission


def rust_char(character: str) -> str:
    """A Rust ``char`` literal, always escaped, so the file is pure ASCII.

    Combining marks and invisible characters in source are unreadable and easy to
    mangle; an escape plus the character's unicode name in a comment is not.
    """
    return f"'\\u{{{ord(character):04x}}}'"


def rust_str(text: str) -> str:
    """A Rust string literal for a macro name (ASCII, may contain quotes)."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def char_name(character: str) -> str:
    try:
        return unicodedata.name(character)
    except ValueError:
        return f"U+{ord(character):04X}"


# -------------------------------------------------------------------- generators


def spacing_clone(combining: str) -> str | None:
    """The standalone (spacing) form of a combining mark, or ``None``.

    Two unicode-sanctioned derivations, in order of authority:

    1. the *spacing clone* proper — a character whose compatibility decomposition
       is ``<compat> SPACE <mark>``, which is precisely unicode's way of saying
       "this is the mark on its own" (``´`` for U+0301, ``˜`` for U+0303);
    2. failing that, the character whose name is the mark's name without the
       ``COMBINING`` prefix (``` ` ``` for COMBINING GRAVE ACCENT, ``ˇ`` for
       COMBINING CARON).  These are the marks whose standalone form predates the
       clone block and therefore carries no decomposition.

    A mark with neither — COMBINING DOT BELOW, COMBINING RIGHT ARROW ABOVE — has no
    standalone form at all, and the accent handler falls back to a space followed
    by the mark itself (PLAN.md §9.3).
    """
    for codepoint in range(0x20, 0x3000):
        candidate = chr(codepoint)
        decomposition = unicodedata.decomposition(candidate).split()
        if (
            len(decomposition) == 3
            and decomposition[0] == "<compat>"
            and decomposition[1] == "0020"
            and chr(int(decomposition[2], 16)) == combining
        ):
            return candidate
    name = unicodedata.name(combining, "")
    if name.startswith("COMBINING "):
        try:
            return unicodedata.lookup(name[len("COMBINING "):])
        except KeyError:
            return None
    return None


def composition_pairs(combining_marks):
    """Every (base, mark, composed) triple that composes under NFC."""
    pairs = []
    for start, stop in COMPOSITION_BASE_RANGES:
        for codepoint in range(start, stop):
            base = chr(codepoint)
            if unicodedata.combining(base):
                continue
            for mark in combining_marks:
                composed = unicodedata.normalize("NFC", base + mark)
                if len(composed) == 1:
                    pairs.append((base, mark, composed))
    return sorted(pairs, key=lambda triple: (ord(triple[0]), ord(triple[1])))


def generate_accents(pylatexenc: Path) -> str:
    """``defs/accents_data.rs`` — the accent tables of PLAN.md §9.3."""
    specs = pylatexenc / "pylatexenc" / "latex2text" / "_defaultspecs.py"
    accents = dedup_sorted(read_literal(specs, "unicode_accents_list"))
    marks = dedup_sorted(
        [(mark,) for _, mark in accents], key=lambda entry: entry[0]
    )
    marks = [mark for (mark,) in marks]

    out = [
        HEADER,
        "//",
        "// Source: pylatexenc `latex2text/_defaultspecs.py`, `unicode_accents_list`,",
        "// plus the composition and spacing-clone facts of the unicode database.",
        "",
        "//! The accent tables (PLAN.md §9.3, §12.4).",
        "//!",
        "//! Three tables, all sorted so that they can be searched by bisection, and all",
        "//! written with escaped characters so that a combining mark cannot be mangled",
        "//! by an editor: what each accent macro installs, what a mark looks like on its",
        "//! own, and what a (base, mark) pair composes to.",
        "",
        "/// The accent macros and the combining mark each one installs.",
        "///",
        "/// Sorted by macro name. The name is written without its escape character, as",
        "/// techy registers it: `\"'\"` is `\\'`.",
        "pub(crate) static ACCENTS: &[(&str, char)] = &[",
    ]
    for name, mark in accents:
        out.append(
            f"    ({rust_str(name)}, {rust_char(mark)}), // {char_name(mark)}"
        )
    out += [
        "];",
        "",
        "/// The standalone (spacing) form of a combining mark, where unicode has one.",
        "///",
        "/// Sorted by the combining mark. A mark that is missing here has no standalone",
        "/// form, and PLAN.md §9.3's fallback — a space followed by the mark — applies.",
        "pub(crate) static ACCENT_SPACING: &[(char, char)] = &[",
    ]
    for mark in marks:
        clone = spacing_clone(mark)
        if clone is None:
            continue
        out.append(
            f"    ({rust_char(mark)}, {rust_char(clone)}),"
            f" // {char_name(mark)} → {char_name(clone)}"
        )
    out += [
        "];",
        "",
        "/// Every (base, mark) pair that composes to a single character under NFC.",
        "///",
        "/// Sorted by `(base, mark)`. This is the whole of the unicode normalization",
        "/// techxt needs: a `no_std` crate carries no unicode database, and the accent",
        "/// rule only ever composes one base character with one of the marks above.",
        "pub(crate) static ACCENT_COMPOSITIONS: &[(char, char, char)] = &[",
    ]
    for base, mark, composed in composition_pairs(marks):
        out.append(
            f"    ({rust_char(base)}, {rust_char(mark)}, {rust_char(composed)}),"
            f" // {char_name(composed)}"
        )
    out += ["];", ""]
    return "\n".join(out)


# name → (relative path under the output root, generator)
GENERATORS = {
    "accents": ("defs/accents_data.rs", generate_accents),
}


# --------------------------------------------------------------------------- main


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "pylatexenc", type=Path, help="path to a pylatexenc checkout (read-only)"
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "rust" / "techxt" / "src",
        help="crate source root to write into (default: rust/techxt/src)",
    )
    parser.add_argument(
        "--only",
        action="append",
        choices=sorted(GENERATORS),
        help="generate only this table (repeatable); default: all of them",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; report whether the committed files are up to date",
    )
    args = parser.parse_args(argv)

    if not (args.pylatexenc / "pylatexenc").is_dir():
        raise SystemExit(f"{args.pylatexenc}: not a pylatexenc checkout")

    stale = False
    for name in args.only or sorted(GENERATORS):
        relative, generate = GENERATORS[name]
        target = args.out / relative
        body = generate(args.pylatexenc)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == body:
            print(f"{relative}: up to date")
            continue
        if args.check:
            stale = True
            print(f"{relative}: OUT OF DATE", file=sys.stderr)
            sys.stderr.writelines(
                difflib.unified_diff(
                    (current or "").splitlines(keepends=True),
                    body.splitlines(keepends=True),
                    fromfile=f"{relative} (committed)",
                    tofile=f"{relative} (generated)",
                )
            )
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        print(f"{relative}: written")

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
